import { type Metadata } from 'next'
import {
  ClerkProvider,
  // SignInButton,
  // SignUpButton,
  // SignedIn,
  // SignedOut,
  // UserButton,
} from '@clerk/nextjs'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className='antialiased'>
          {children}
          <Toaster /> 
        </body>
      </html>
    </ClerkProvider>
  )
}